import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});
const report={date:new Date().toISOString(),checks:[],errors:[],desktop:[],mobile:[],limitations:['Mobile emulation on desktop Chrome; real iOS/Android hardware not tested.']};
const check=(name,v)=>{assert.ok(v,name);report.checks.push(name);console.log('PASS',name)};
const state=p=>p.evaluate(()=>window.__museum.state());
const watch=p=>p.on('pageerror',e=>report.errors.push(e.message));
async function ready(p){await p.waitForFunction(()=>window.__museum?.state().loaded,{},{timeout:60000});await p.waitForTimeout(1200)}
async function chapter(p,i){await p.evaluate(i=>scrollTo({top:document.querySelectorAll('.chapter')[i].offsetTop,behavior:'instant'}),i);await p.waitForFunction(i=>Math.abs(window.__museum.state().progress-i)<.001,i);await p.waitForTimeout(550)}
try{
 const p=await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1});watch(p);await p.goto('http://127.0.0.1:4186');await ready(p);
 let s=await state(p);check('Desktop GLB loads with all five semantic roots',s.loaded&&Object.keys(s.roots).length===5);check('All model meshes retain UV coordinates',s.meshCount===s.uvMeshes);check('Correct converted metric scale',s.bounds[0]>1.6&&s.bounds[0]<1.7&&s.bounds[1]>.25&&s.bounds[1]<.3);
 for(let i=0;i<6;i++){await chapter(p,i);s=await state(p);check(`Desktop chapter ${i+1}`,s.active===i&&!s.error);check(`Desktop chapter ${i+1} document width`,await p.evaluate(()=>document.documentElement.scrollWidth===innerWidth));await p.screenshot({path:`qa/desktop-${i+1}.png`});report.desktop.push(s)}
 await p.locator('#free-explore').click();check('Free exploration enters',(await state(p)).exploring);await p.mouse.move(600,450);await p.mouse.down();await p.mouse.move(850,450,{steps:12});await p.mouse.up();await p.waitForTimeout(600);check('Drag rotates real model',Math.abs((await state(p)).yaw)>.4);await p.locator('#reset-view').click();await p.waitForTimeout(1200);check('Reset restores angle',Math.abs((await state(p)).yaw)<.005);await p.keyboard.press('Escape');check('Escape exits exploration',!(await state(p)).exploring);
 for(let i=4;i>=0;i--){await chapter(p,i);s=await state(p);check(`Reverse scroll ${i+1}`,s.active===i);if(i!==2)check(`Assembled outside structure ${i+1}`,s.roots.Roof_Root[1]===0)}
 await p.locator('nav a[href="#architecture"]').click();await p.waitForTimeout(1800);check('Nav scrolls to architecture',(await state(p)).active===2);await p.waitForFunction(()=>window.__museum.state().explosion===1);check('Exterior separation only known layers',(await state(p)).roots.Skylight_Root[1]===18);await p.locator('#assembled').click();await p.waitForFunction(()=>window.__museum.state().explosion===0);check('Assembly control restores original coordinates',(await state(p)).roots.Roof_Root[1]===0);await p.locator('#separated').click();await p.waitForFunction(()=>window.__museum.state().explosion===1);check('Separation control works',true);
 await chapter(p,3);const firstCamera=(await state(p)).camera;await p.locator('[data-detail="1"]').click();await p.waitForTimeout(1200);check('Material focus moves camera',Math.abs((await state(p)).camera[0]-firstCamera[0])>.1);await p.locator('#zoom').click();await p.waitForTimeout(1000);check('Detail zoom state',(await state(p)).zoom);await p.locator('[data-detail="0"]').click();
 await chapter(p,4);await p.locator('[data-story="1"]').click();check('Value card opens real content',await p.locator('#story-dialog').isVisible());check('Dialog contains matching story',(await p.locator('#story-dialog h2').textContent())==='景观相连');await p.keyboard.press('Escape');check('Dialog closes',!(await p.locator('#story-dialog').isVisible()));
 await chapter(p,1);await p.mouse.wheel(0,320);await p.waitForTimeout(1000);s=await state(p);check('Scroll has continuous fractional camera states',s.progress>1.1&&s.progress<1.7);await p.mouse.wheel(0,-320);await p.waitForTimeout(1000);check('Reverse wheel stable',Math.abs((await state(p)).progress-1)<.01);
 const phone=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});watch(phone);await phone.goto('http://127.0.0.1:4186');await ready(phone);check('Phone loads mobile LOD',(await state(phone)).modelVariant==='mobile');
 for(let i=0;i<6;i++){await chapter(phone,i);s=await state(phone);const layout=await phone.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,title:document.querySelector('.chapter.active h1,.chapter.active h2').getBoundingClientRect().toJSON(),canvas:document.querySelector('#stage').getBoundingClientRect().toJSON(),controls:[...document.querySelectorAll('.chapter.active .button,.chapter.active .segmented')].map(el=>el.getBoundingClientRect().toJSON())}));check(`Phone ${i+1} no horizontal overflow`,!layout.overflow);check(`Phone ${i+1} title readable`,layout.title.top>78&&layout.title.bottom<innerHeightSafe());check(`Phone ${i+1} controls within viewport`,layout.controls.every(r=>r.left>=0&&r.right<=390&&r.bottom<=844));if(i!==4)check(`Phone ${i+1} title above 3D`,layout.title.bottom<layout.canvas.top);await phone.screenshot({path:`qa/mobile-${i+1}.png`});report.mobile.push({...s,layout})}
 await phone.locator('.menu-toggle').tap();await phone.locator('nav a[href="#architecture"]').tap();await phone.waitForTimeout(1800);check('Phone navigation works',(await state(phone)).active===2);check('Phone menu closes after choice',await phone.locator('.menu-toggle').getAttribute('aria-expanded')==='false');
 const cdp=await phone.context().newCDPSession(phone);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:190,y:590}]});for(let y=540;y>=250;y-=40)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:190,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await phone.waitForTimeout(1100);check('Native touch scroll moves through chapters',(await state(phone)).progress>2.1);
 await phone.setViewportSize({width:360,height:740});await chapter(phone,2);check('Small phone no overflow',await phone.evaluate(()=>document.documentElement.scrollWidth===innerWidth));await phone.screenshot({path:'qa/mobile-small.png'});
 const fail=await browser.newPage({viewport:{width:1280,height:800}});watch(fail);await fail.route('**/museum-*.glb',r=>r.fulfill({status:503,body:'Unavailable'}));await fail.goto('http://127.0.0.1:4186');await fail.locator('#retry').waitFor({state:'visible'});check('Failure leaves readable heading and poster',await fail.locator('h1').isVisible()&&await fail.locator('.poster').isVisible());await fail.screenshot({path:'qa/fallback.png'});await fail.unroute('**/museum-*.glb');await fail.locator('#retry').click();await ready(fail);check('Retry recovers model',(await state(fail)).loaded);await fail.close();
 const noGL=await browser.newPage({viewport:{width:1280,height:800}});watch(noGL);await noGL.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){if(type==='webgl2'||type==='webgl')return null;return original.call(this,type,...args)}});await noGL.goto('http://127.0.0.1:4186');await noGL.locator('#retry').waitFor({state:'visible'});check('No-WebGL fallback preserves full content',await noGL.locator('h1').isVisible());await noGL.close();
 const rm=await browser.newPage({viewport:{width:1280,height:800},reducedMotion:'reduce'});watch(rm);await rm.goto('http://127.0.0.1:4186/#architecture');await ready(rm);check('Reduced motion and deep link',(await state(rm)).active===2);await rm.close();
 check('No uncaught JS errors',report.errors.length===0);report.passed=true;
}catch(e){report.passed=false;report.failure=e.stack;console.error(e);process.exitCode=1}finally{await fs.writeFile('qa/report.json',JSON.stringify(report,null,2));await browser.close()}
function innerHeightSafe(){return 844}
